packages:
  - packages/*

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma
  - tree-sitter
  - vue-demi

syncInjectedDepsAfterScripts:
  - build
